name: build-deploy

on:
  push:
    branches: [main]

jobs:
  use-build:
    uses: fifikim/http-server/.github/workflows/build.yml@main

  deploy-and-run:
    needs: use-build
    runs-on: ubuntu-latest

    steps:
      - name: Execute gradle build on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd http-server
            git pull
            ./gradlew build
            java -jar build/libs/http-server.jar