name: build

on:
  workflow_call:
  push:
    branches-ignore: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run the linter for source code
        run: ./gradlew checkstyleMain

      - name: Run the linter for tests
        run: ./gradlew checkstyleTest

      - name: Run test suite
        run: ./gradlew test

      - name: Build with Gradle wrapper
        run: ./gradlew build

      - name: Run server in background
        run: java -jar build/libs/http-server.jar &

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
        with:
          ruby-version: '2.7'

      - name: Run Spinach acceptance tests
        run: |
          cd http-server-spec
          bundle install
          rake test:implemented