name: build-deploy

on:
  push:
    branches: [main]

jobs:
  use-build:
    uses: fifikim/http-server/.github/workflows/build.yml@main

  deploy-and-run:
    needs: use-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle wrapper
        run: ./gradlew build

      - name: Upload static file directory to production server
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'web'
          remote: 'web'
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}

      - name: Upload JAR artifact to production server
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'build/libs/http-server.jar'
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          pre_upload: lsof -i:5000 -t | xargs -r kill
          post_upload: java -jar http-server.jar

