name: build-deploy

on:
  push:
    branches: [main]

jobs:
  use-build:
    uses: fifikim/http-server/.github/workflows/build.yml@main

  deploy-and-run:
    needs: use-build
    runs-on: ubuntu-latest

    steps:
      - uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: './build/libs/http-server.jar'
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          post_upload: java -jar build/libs/http-server.jar

