name: Java CI

on:
  [push, pull_request]

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run the linter for source code
        run: ./gradlew checkstyleMain

      - name: Run the linter for tests
        run: ./gradlew checkstyleTest

      - name: Run test suite
        run: ./gradlew test

      - name: Build with Gradle wrapper
        run: ./gradlew build